spring:
  application.name: customers-ws
  security:
    user:
      name: admin
      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"

# local testing
# eureka.client.serviceUrl.defaultZone: http://localhost:7100/eureka

# heroku deployment
eureka.client.serviceUrl.defaultZone: https://eureka-ws.herokuapp.com/eureka

server:
  port: ${PORT:7001}