spring:
  application.name: customers-ws
  security:
    user:
      name: admin
      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  # local testing
  #client.serviceUrl.defaultZone: http://localhost:7100/eureka
  # heroku deployment
  client.serviceUrl.defaultZone: https://eureka-ws.herokuapp.com/eureka
  instance:
    hostname: ${DOMAIN_NAME:customers-ws.herokuapp.com}

server:
  port: ${PORT:7001}